---
# Create user accounts
- name: Create new users accounts 
  hosts: localhost 
  remote_user: ansibletarget1
  
  tasks:
  - name: create managers group
    group:
      name: managers
      state: present
 
  - name: create manage user  
    user:  
      name: manager1
      state: present

  - name: create manager user
    user:
      name: manager2
      state: present

  - name: create admins group with sudo access
    become: yes
    group:
      name: admins with sudo access
      state: present

  - name: create admin user
    user:
      name: admin
      state: present

  - name: create devs group with no sudo access
    group:
      name: devs with no sudo access  
      state: present
  
  - name: create devs user
    user:
      name: devs
      state: present

# Install software needed for devolopers  
- name: Install software packages for developers
  hosts: localhost
  remote_user: ansibletarget1
  
  tasks:
  - name: Install specific software packages
    package: 
      name: 
        - git
        - vim
        - curl 
        - htop
        - tree
        - tmux
        - unzip 
        - docker.io
      state: latest  

# Set MOTD  
- name: Set MOTD
  hosts: localhost  
  remote_user: ansibletarget1

  tasks:
  - name: Set MOTD 
    file:
      path: /etc/motd
      line: "Welcome to the DevOps workstation."
 

# Set Hostname  
- name: Set a hostname for Ubuntu
  hosts: localhost  
  remote_user: ansibletarget1

  tasks:
  - name: Set hostname to "devops_1"
    ansible.builtin.hostname:
      name: devops_1
      use: Ubuntu       

- name: Set a hostname for CentOS
  hosts: localhost  
  remote_user: ansibletarget1

  tasks:
  - name: Set hostname to "devops_2"
    ansible.builtin.hostname:
      name: devops_2
      use: CentOS

# Set timezone to UTC 
- name: Set timezone to UTC
  hosts: localhost  
  remote_user: ansibletarget1

  tasks:
  - name: Set a timezone to UTC
    community.general.timezone:
      name: Etc/UTC

# Special requirement 
- name: Install MariaDB 
  hosts: localhost  
  remote_user: ansibletarget1

  tasks:
  - name: Create MariaDB with admin user 
    user:
      name: admin
      host: 'localhost'

      state: present
      password: your_strong_password

  - name: Grant privileges to MariaDB user
    user:
      name: admin
      host: 'localhost'

      state: present 
