---
- name: Create User Accounts and Provision Servers
  hosts: all 
  become: yes 
  
# Task 1  
  tasks:
    - name: Create Managers, Admins and Devs groups
      group:
        name: "{{ item }}"
        state: present
      loop:
        - managers 
        - admins 
        - devs 
 
    - name: Create Manager Users  
      user:  
        name: "{{ item }}"
        state: present
        group: managers
        groups: "{{ 'wheel' if ansible_os_family == 'RedHat' else 'sudo' }}"    
        append: yes 
      loop:
        - manager1
        - manager2

    - name: Create Admins Users with sudo access
      user:
        name: admin
        state: present
        group: admins
        groups: "{{ 'wheel' if ansible_os_family == 'RedHat' else 'sudo' }}"
        append: yes 

    - name: Create Devs Users with no sudo access
      user:
        name: user
        group: devs

# Task 2
    - name: Install Software for Developers
      package:
        name: "{{ item }}"
        state: present
      loop:
        - vim
        - nano
        - git
        - curl
        - tree
        - vim
        - tmux
        - unzip

# Task 3
    - name: Set MOTD 
      shell: echo 'Welcome to the DevOps workstation.' > /etc/motd
      args:
        creates: /etc/motd

# Task 4
    - name: Set Hostname to "devops_1" for CentOS
      hostname:
        name: devops1
      when: ansible_facts['os_family'] == "RedHat"

# Task 5
    - name: Set timezone to UTC
      timezone:
        name: UTC

# Task 6
    - name: Install MariaDB on CentOS
      yum:
        name: mariadb-server
        state: present
        update_cache: yes 
      when: ansible_facts['os_family'] == 'RedHat'
