---
# Create user accounts 
- hosts: all
- name: Create users for managers group
  user:
    name: manager1
    group: managers
    state: present
  user:  
    name: manager2
    group: managers
    state: present

- name: Create users for admins with sudo access
  become: yes
  user:
    name: admin
    group: admins with sudo access
    state: present

- name: Create users for devs with no sudo access
  user:
    name: user  
    group: devs with no sudo access
  become: yes

# Install software needed for devolopers  
- name: "Install software packages for developers
  package: 
    name: 
      - git
      - vim
      - curl 
      - htop
      - tree
      - tmux
      - unzip 
      - docker.io
    state: latest  

# Set MOTD  
- name: Set MOTD
    path:/etc/motd
    line:"Welcome to the DevOps workstation."
  become: yes

# Set Hostname  
- name: Set a hostname 
  hosts: all
  tasks:
    - name: Set hostname to "devops_1"
      ansible.builtin.hostname:
        name: devops_1
        use: Ubuntu       

- name: Set a hostname 
  hosts: all
  tasks:
    - name: Set hostname to "devops_2"
      ansible.builtin.hostname:
        name: devops_2
        use: CentOS

# Set timezone to UTC     
- name: Set timezone to UTC
  community.general.timezone:
    name: Etc/UTC

#Special requirement     
- hosts: target
  become: true
  tasks:
    - name: Create MariaDB user
        name: 'admin'
        host: 'localhost'
        state: present
        password: your_strong_password

    - name: Grant privileges to MariaDB user
        name: 'admin'
        host: 'localhost'
        state: present   